version: "3.9"

services:
  mysql:
   image: mysql/mysql-server
   ports:
     - "3306:3306"
   #estart: always
   command:
      - mysqld
      - --max_connections=3000
      - --wait_timeout=600
      - --interactive_timeout=600
      - --thread_cache_size=50
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
   environment:
      - MYSQL_DATABASE=blog
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=zhang
      - MYSQL_PASSWORD=Zhang.123
   volumes:
      - /home/data/mysql/data:/var/lib/mysql       #将容器中运行的mysql数据保存到宿主机，防止容器删除后数据丢失
      - /home/data/conf:/etc/my.conf.d 
   networks:
       - Django
   container_name: mysql

  web:
    container_name: Yolo_web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    environment:
      - POSTGRES_NAME=blog
      - POSTGRES_USER=zhang
      - POSTGRES_PASSWORD=Zhang.123
    ports:
      - "8000:8000"
    networks:
       - Django
    depends_on:
       - mysql
    #ontainer_name: Yolo_web

networks:
  Django:
   external: true