# Generated by Django 3.2 on 2022-04-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20220419_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='文章链接'),
        ),
    ]
