# Generated by Django 3.2 on 2022-05-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_articles_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='a_unique_id',
            field=models.CharField(blank=True, help_text='其他平台的唯一登陆id', max_length=64, null=True, verbose_name='id'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='avatar_url',
            field=models.URLField(help_text='可能是其他平台的头像', null=True, verbose_name='用户头像'),
        ),
    ]
