# Generated by Django 3.2 on 2022-05-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_userinfo_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='sign_status',
            field=models.IntegerField(choices=[(0, '用户名注册'), (1, '手机号注册'), (2, '邮箱注册'), (3, 'QQ注册'), (4, 'gitee登陆')], default=0, verbose_name='注册方式'),
        ),
    ]
