# Generated by Django 3.2 on 2022-05-11 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_alter_userinfo_sign_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navs',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='navs',
            name='nav_category',
        ),
        migrations.DeleteModel(
            name='NavCategory',
        ),
    ]
