# Generated by Django 3.2 on 2022-05-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20220511_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='navs',
            name='collects_count',
            field=models.IntegerField(default=0, verbose_name='收藏数'),
        ),
        migrations.AddField(
            model_name='navs',
            name='digg_count',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.CreateModel(
            name='NavTags',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=10, verbose_name='网络标签名称')),
                ('tag', models.ManyToManyField(to='app01.NavTags', verbose_name='网站标签')),
            ],
        ),
    ]
