# Generated by Django 3.2 on 2022-05-11 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_auto_20220511_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navtags',
            options={'verbose_name_plural': '网站标签'},
        ),
    ]
