# Generated by Django 3.2 on 2022-05-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_alter_navtags_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navtags',
            name='tag',
        ),
        migrations.AddField(
            model_name='navs',
            name='tag',
            field=models.ManyToManyField(to='app01.NavTags', verbose_name='网站标签'),
        ),
        migrations.AlterField(
            model_name='navtags',
            name='title',
            field=models.CharField(max_length=16, null=True, verbose_name='网络标签名称'),
        ),
    ]
